### ISSUE TITLE
Having problems

### ISSUE THREAD

**Issue by Steve-Wax** [kbjunky/ADNS9800#1]
I had a couple of your boards made up from the gerbers and I'm trying to get them to work with the Aball firmware.  Having trouble gettiing it to work.  I will attach a photo of one of the boards I made.  Any suggestions for trouble shooting
![IMG_1431](https://user-images.githubusercontent.com/52845023/163050761-0c92f0bf-a2c4-45f7-a4b6-a14cb3d38bcf.JPG)
?

**Comment by kbjunky** [comment]
Looking at the board it seems like you haven't used electrolyte capacitors. There are few on the board. Can you tell me what is happening? This sensor is very sensitive to the Z distance. So if you are using it in a trackball the ball should be within 2.18-2.62 distance. If it's totally dead then I would suggest starting replacing caps to the proper ones. Checking soldering especially around the transistor. This one is  super difficult to solder because of the size. You can also compare your voltage values to the ones provided in the [datasheet](https://www.mouser.sg/datasheet/2/678/Avagotechnologie_ADNS-9800-1217258.pdf) p.10. I assume you also got the lens with the chip?

**Comment by Steve-Wax** [comment]
Thanks for your response and the design of the board.  It is totally dead.  With the lens on (it came with the sensor) I see no mouse movement when swiping my finger across it.  I think the soldering is good after inspecting it under magnification.  I used solder paste and hot air to do the soldering.  I did use all ceramic capacitors.  Looking at your drawing it seems like C2, C8, C9, C10, and C11 need to be electrolytic.  Is that correct?

**Comment by kbjunky** [comment]
Yes, these are electrolytic. If you have the multimeter check voltages on the sensor. Can you share which ABall firmware you are using? Is it this one https://github.com/brickbots/qmk_firmware/tree/aball/keyboards/handwired/aball ?

**Comment by Steve-Wax** [comment]
Yes that is the firmware I'm using.  I checked VDD5 and VDDIO and both are in range.  Looks like I will need to buy some new capacitors.

**Comment by kbjunky** [comment]
I have just checked this firmware with my sensor (same PCB as yours,  5V). It works OK. So most probably the problem is with your hardware.
